parameters:
    darvin_menu.breadcrumbs.provider.class:     Darvin\MenuBundle\Breadcrumbs\BreadcrumbsMenuProvider
    darvin_menu.breadcrumbs.provider.menu_name: darvin_menu_breadcrumbs

    darvin_menu.breadcrumbs.twig_extension.class: Darvin\MenuBundle\Twig\Extension\BreadcrumbsExtension

services:
    darvin_menu.breadcrumbs.provider:
        class: "%darvin_menu.breadcrumbs.provider.class%"
        arguments:
            - "@service_container"
            - "@knp_menu.matcher"
            - "@darvin_menu.configuration.menu"
            - "@darvin_menu.item_factory.root"
            - "%darvin_menu.breadcrumbs.provider.menu_name%"
        tags:
            - { name: knp_menu.provider }

    darvin_menu.breadcrumbs.twig_extension:
        class:  "%darvin_menu.breadcrumbs.twig_extension.class%"
        public: false
        arguments:
            - "@darvin_menu.breadcrumbs.provider"
            - "@knp_menu.helper"
            - "%darvin_menu.breadcrumbs.provider.menu_name%"
            - "%darvin_menu.template.breadcrumbs%"
        tags:
            - { name: twig.extension }
