parameters:
    darvin_menu.builder.abstract.class: Darvin\MenuBundle\Builder\Builder

services:
    darvin_menu.builder.abstract:
        class:    "%darvin_menu.builder.abstract.class%"
        abstract: true
        arguments:
            - "@darvin_utils.custom_object.loader"
            - "@doctrine.orm.entity_manager"
            - "@knp_menu.factory"
            - "@darvin_utils.locale.provider"
            - "@darvin_content.translatable.translation_joiner"
