parameters:
    darvin_menu.builder.abstract.class: Darvin\MenuBundle\Builder\Builder

services:
    _defaults:
        public: true

    darvin_menu.builder.abstract:
        class:    '%darvin_menu.builder.abstract.class%'
        abstract: true
        public:   false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@darvin_utils.orm.entity_resolver'
            - '@darvin_menu.item_factory.pool'
            - '@darvin_utils.locale.provider'
            - '@darvin_utils.mapping.metadata_factory'
            - '@property_accessor'
            - '@darvin_menu.slug_map.object_loader'
            - '@stof_doctrine_extensions.listener.sortable'
            - '%darvin_menu.entities%'
