parameters:
    darvin_menu.configuration.association.class: Darvin\MenuBundle\Configuration\AssociationConfiguration

    darvin_menu.configuration.menu.class: Darvin\MenuBundle\Configuration\MenuConfiguration

services:
    darvin_menu.configuration.association:
        class: "%darvin_menu.configuration.association.class%"
        arguments:
            - "@darvin_admin.entity_namer"
            - "%darvin_menu.associations%"

    darvin_menu.configuration.menu:
        class: "%darvin_menu.configuration.menu.class%"
        arguments:
            - "%darvin_menu.menus%"
