parameters:
    darvin_menu.menu.abstract.class: Knp\Menu\MenuItem

services:
    darvin_menu.menu.abstract:
        class:    "%darvin_menu.menu.abstract.class%"
        abstract: true
        arguments:
            - "@request_stack"
