parameters:
    darvin_menu.item_factory.abstract.class: Darvin\MenuBundle\Item\Factory\AbstractItemFactory

    darvin_menu.item_factory.string.class: Darvin\MenuBundle\Item\Factory\StringItemFactory

    darvin_menu.item_factory.abstract_entity.class: Darvin\MenuBundle\Item\Factory\Entity\AbstractEntityItemFactory

    darvin_menu.item_factory.menu_item_entity.class: Darvin\MenuBundle\Item\Factory\Entity\MenuItemFactory

    darvin_menu.item_factory.slug_map_item_entity.class: Darvin\MenuBundle\Item\Factory\Entity\SlugMapItemFactory

    darvin_menu.item_factory.pool.class: Darvin\MenuBundle\Item\Factory\Pool\ItemFactoryPool

services:
    darvin_menu.item_factory.abstract:
        class:    '%darvin_menu.item_factory.abstract.class%'
        abstract: true
        calls:
            - [ setGenericItemFactory, [ '@knp_menu.factory' ] ]

    darvin_menu.item_factory.string:
        class:  '%darvin_menu.item_factory.string.class%'
        parent: darvin_menu.item_factory.abstract
        tags:
            - { name: darvin_menu.item_factory }

    darvin_menu.item_factory.abstract_entity:
        class:    '%darvin_menu.item_factory.abstract_entity.class%'
        parent:   darvin_menu.item_factory.abstract
        abstract: true
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager' ] ]
            - [ setObjectNamer,   [ '@darvin_utils.object_namer' ] ]
            - [ setSlugMapRouter, [ '@darvin_content.router.slug_map' ] ]

    darvin_menu.item_factory.menu_item_entity:
        class:  '%darvin_menu.item_factory.menu_item_entity.class%'
        parent: darvin_menu.item_factory.abstract_entity
        arguments:
            - '@request_stack'
        tags:
            - { name: darvin_menu.item_factory }

    darvin_menu.item_factory.slug_map_item_entity:
        class:  '%darvin_menu.item_factory.slug_map_item_entity.class%'
        parent: darvin_menu.item_factory.abstract_entity
        tags:
            - { name: darvin_menu.item_factory }

    darvin_menu.item_factory.pool:
        class: '%darvin_menu.item_factory.pool.class%'
