index_view_row_attr:
    - level
menu:
    skip: true
pagination:
    enabled: false
searchable_fields:
    - title
    - url
sorter:
    id:     darvin_menu.admin.menu_item_sorter
    method: sort
order_by:
    menu:     asc
    level:    asc
    position: asc
joins:
    hover_image:       hoverImage
    hover_image_sizes: hover_image.sizes
    image:             image
    image_sizes:       image.sizes
    slug_map_item:     slugMapItem
view:
    index:
        fields:
            menuTitle:    ~
            position:     ~
            enabled:      ~
            showChildren: ~
            entity:
                widget:
                    alias: menu_item_entity_link
            title: ~
            url:
                widget:
                    alias: simple_link
    show:
        fields:
            menuTitle:    ~
            enabled:      ~
            showChildren: ~
            title:        ~
            url:
                widget:
                    alias: simple_link
form:
    index:
        fields:
            position:
                options:
                    attr:
                        class: position
            enabled:      ~
            showChildren: ~
    filter:
        fields:
            menu:
                type: Darvin\MenuBundle\Form\Type\Admin\MenuType
            enabled:      ~
            showChildren: ~
            title:
                compare_strict: false
            url:
                compare_strict: false
    edit:
        fields:
            menu:
                type: Darvin\MenuBundle\Form\Type\Admin\MenuType
            parent:
                options:
                    required: false
            slugMapItem:
                type: Darvin\MenuBundle\Form\Type\Admin\SlugMapItemType
            showChildren:
                options:
                    required: false
            translations:
                type: A2lix\TranslationFormBundle\Form\Type\TranslationsType
                options:
                    label: false
                    fields:
                        enabled: ~
                        title:   ~
                        url:     ~
            image:
                type: Darvin\ImageBundle\Form\Type\Image\ImageType
                options:
                    data_class: Darvin\MenuBundle\Entity\Menu\MenuItemImage
            hoverImage:
                type: Darvin\ImageBundle\Form\Type\Image\ImageType
                options:
                    data_class: Darvin\MenuBundle\Entity\Menu\MenuItemImage
