index_view_new_form: true
menu:
    skip: true
order_by:
    menu:     asc
    position: asc
sortable_fields:
    position:     ~
    menuTitle:    menu
    enabled:      translations.enabled
    showChildren: ~
    associated:   associatedClass
    title:        translations.title
    url:          translations.url
view:
    index:
        fields:
            position:     ~
            menuTitle:    ~
            enabled:      ~
            showChildren: ~
            associated:
                widget:
                    alias: menu_associated
            title: ~
            url:   ~
    show:
        fields:
            menuTitle:    ~
            enabled:      ~
            showChildren: ~
            associated:
                widget:
                    alias: menu_associated
            title: ~
            url:
                widget:
                    alias: simple_link
form:
    index:
        fields:
            position: ~
            enabled:
                type: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            showChildren:
                type: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            title: ~
            url:   ~
    filter:
        fields:
            positionFrom: ~
            positionTo:   ~
            menu:
                type: Darvin\MenuBundle\Form\Type\Admin\MenuType
            enabled:      ~
            showChildren: ~
            title:
                compare_strict: false
            url:
                compare_strict: false
    edit:
        fields:
            menu:
                type: Darvin\MenuBundle\Form\Type\Admin\MenuType
            associated:
                type: Darvin\MenuBundle\Form\Type\Admin\AssociatedType
            showChildren: ~
            translations:
                type: A2lix\TranslationFormBundle\Form\Type\TranslationsType
                options:
                    label: false
                    fields:
                        enabled: ~
                        title:
                            attr:
                                autofocus: true
                        url: ~
    new:
        fields:
            menu:
                type: Darvin\MenuBundle\Form\Type\Admin\MenuType
            associated:
                type: Darvin\MenuBundle\Form\Type\Admin\AssociatedType
            showChildren: ~
            translations:
                type: A2lix\TranslationFormBundle\Form\Type\TranslationsType
                options:
                    label: false
                    fields:
                        enabled: ~
                        title:   ~
                        url:     ~
