index_view_new_form: true
menu:
    skip: true
joins:
    hover_image:       hoverImage
    hover_image_sizes: hover_image.sizes
    image:             image
    image_sizes:       image.sizes
order_by:
    menu: asc
searchable_fields:
    - title
    - url
sortable_fields:
    menuTitle:    menu
    enabled:      translations.enabled
    showChildren: ~
    title:        translations.title
    url:          translations.url
view:
    index:
        fields:
            menuTitle:    ~
            enabled:      ~
            showChildren: ~
            title:        ~
            url:          ~
            image:
                widget:
                    alias: image_link
                    options:
                        property: image
            hoverImage:
                widget:
                    alias: image_link
                    options:
                        property: hoverImage
    show:
        fields:
            menuTitle:    ~
            enabled:      ~
            showChildren: ~
            title:        ~
            url:
                widget:
                    alias: simple_link
form:
    index:
        fields:
            enabled:      ~
            showChildren: ~
    filter:
        fields:
            menu:
                type: Darvin\MenuBundle\Form\Type\Admin\MenuType
            enabled:      ~
            showChildren: ~
            title:
                compare_strict: false
            url:
                compare_strict: false
    new:
        fields:
            menu:
                type: Darvin\MenuBundle\Form\Type\Admin\MenuType
            slugMapItem:
                type: Darvin\MenuBundle\Form\Type\Admin\SlugMapItemType
            showChildren:
                options:
                    required: false
            translations:
                type: A2lix\TranslationFormBundle\Form\Type\TranslationsType
                options:
                    label: false
                    fields:
                        enabled: ~
                        title:   ~
                        url:     ~
            image:
                type: Darvin\ImageBundle\Form\Type\Image\ImageType
                options:
                    data_class: Darvin\MenuBundle\Entity\Menu\MenuItemImage
            hoverImage:
                type: Darvin\ImageBundle\Form\Type\Image\ImageType
                options:
                    data_class: Darvin\MenuBundle\Entity\Menu\MenuItemImage
