darvin_admin:
    menu:
        groups:
            -
                name:     menu
                position: 20
                colors:
                    main:    "#cb9023"
                    sidebar: "#a4ce23"
                icons:
                    main:    bundles/darvinmenu/images/admin/menu_group_main.png
                    sidebar: bundles/darvinmenu/images/admin/menu_group_sidebar.png
    sections:
        -
            entity: Darvin\MenuBundle\Entity\Menu\Item
            config: "@DarvinMenuBundle/Resources/config/admin/menu/item.yml"
